<?php

namespace RRZE\vRevision;

defined('ABSPATH') || exit;

/**
 * Word-Collection for Rabbithole.php
 * Words are used to generate Text-Content
 */
class Alice{
    public static function getMainWords() {
        $main = array(
            'Alice',
            'Schwester',
            'Bilder',
            'Gespräche',
            'Gänseblümchen',
            'Kette',
            'Kaninchen',
            'Augen',
            'Mühe',
            'Westentasche',
            'Grasplatz',
            'Neugierde',
            'Kaninchenbau',
            'Landkarten',
            'Küchenschränken',
            'Bücherbrettern',
            'Töpfchen',
            'Aufschrift',
            'Apfelsinen',
            'Miez',
            'adäquat',
            'Adresse',
            'Agentur',
            'Aggression',
            'aggressiv',
            'akquirieren',
            'Akquise',
            'Akquisition',
            'Akupunktur',
            'akustisch',
            'Albtraum',
            'am besten',
            'angsterfüllt',
            'anhand',
            'Annalen',
            'annullieren',
            'Anschluss',
            'Antipathie',
            'Apparat',
            'Ärgernis',
            'Armatur',
            'Arzt',
            'asozial',
            'Asymmetrie',
            'asymmetrisch',
            'Atmosphäre',
            'Attrappe',
            'auf einmal',
            'aufgrund',
            'aufgrund dessen',
            'aufhören',
            'aufrechterhalten',
            'aufhören',
            'aufrechterhalten',
            'Aufwand',
            'aufwendig',
            'außerdem',
            'Autor',
            'autorisieren',
            'avisieren',
            'Ballett',
            'barfuß',
            'Barzahlung',
            'Beeinflussung',
            'Beredsamkeit',
            'Bescheid',
            'Bezug nehmend',
            'Billard',
            'bis auf Weiteres',
            'Biskuit',
            'bisschen',
            'bloß',
            'Brezel',
            'Brillant',
            'brillant',
            'Büfett',
            'Charisma',
            'Chrysantheme',
            'Dankeschön',
            'darüber hinaus',
            'dass',
            'definitiv',
            'delegieren',
            'Delegierter',
            'dementsprechend',
            'derselbe',
            'des Weiteren',
            'detailliert',
            'dezidiert',
            'diffizil',
            'Dilettant',
            'dilettantisch',
            'diskriminieren',
            'eben',
            'Eiffelturm',
            'eigentlich',
            'einmal',
            'einzig',
            'Ekstase',
            'Elefant',
            'E-Mail',
            'Empathie',
            'endgültig',
            'endlich',
            'Entgelt',
            'Epidemie',
            'Ergebnis',
            'erst mal',
            'essenziell',
            'explizit',
            'extrovertiert',
            'exzellent',
            'Fronleichnam',
            'Fuß',
            'Fußball',
            'Galerie',
            'Galionsfigur',
            'galoppieren',
            'Gebaren',
            'gebären',
            'gegebenenfalls',
            'Gehör',
            'Geisel',
            'Geiselnahme',
            'Geißel',
            'geißeln',
            'Geißelung',
            'Gelatine',
            'gemäß',
            'genießen',
            'Geratewohl',
            'gesamt',
            'Ginkgo',
            'googeln',
            'Gratwanderung',
            'griesgrämig',
            'Grieß',
            'grölen',
            'Guerillakrieg',
            'Häkchen',
            'Hals über Kopf',
            'hältst',
            'hanebüchen',
            'heißen',
            'heute Morgen',
            'hoffentlich',
            'hören',
            'ihrerseits',
            'im Einzelnen',
            'im Folgenden',
            'im Voraus',
            'im Wesentlichen',
            'immer noch',
            'in puncto',
            'Inbus',
            'Inbusschraube',
            'infolge',
            'infolgedessen',
            'infrage',
            'Inkrafttreten',
            'insbesondere',
            'insgesamt',
            'interessant',
            'Interesse',
            'inwieweit',
            'Jackett',
            'Joghurt',
            'Kaninchen',
            'Kannibale',
            'Karosserie',
            'Karussell',
            'katastrophal',
            'Katastrophe',
            'kennenlernen',
            'Kenntnis',
            'kohärent',
            'kolossal',
            'Komitee',
            'Kommentar',
            'Kommilitone',
            'Konkurrenz',
            'Konsens',
            'konstatieren',
            'kopfüber',
            'korrigieren',
            'Koryphäe',
            'krakeelen',
            'Kreißsaal',
            'Kumulation',
            'kumulieren',
            'Kuss',
            'Lappalie',
            'Lärche (Baum)',
            'lässt',
            'Lerche (Vogel)',
            'Libyen',
            'Lid',
            'Lizenz',
            'lizenzieren',
            'mahlen',
            'Mandarine',
            'Maschine',
            'mindeste',
            'minimal',
            'Mischpoke',
            'Misere',
            'miteinbeziehen',
            'mithilfe',
            'Mobiliar',
            'morgendlich',
            'nach Hause',
            'nach wie vor',
            'nämlich',
            'nichtsdestotrotz',
            'noch mal',
            'Obolus',
            'obsolet',
            'ohne Weiteres',
            'opponieren',
            'Paket',
            'Paneel',
            'Pappenstiel',
            'Papst',
            'parallel',
            'peripher',
            'persönlich',
            'Philippinen',
            'piken',
            'piksen',
            'Pinnwand',
            'platzieren',
            'Platzierung',
            'Pogrom',
            'Portemonnaie',
            'Portfolio',
            'potenzial',
            'potenziell',
            'präferieren',
            'Prämisse',
            'projizieren',
            'prophylaktisch',
            'Prozess',
            'Pubertät',
            'Quarzuhr',
            'rau',
            'recht haben',
            'Reflexion',
            'renommiert',
            'Rentier',
            'Reparatur',
            'respektive',
            'Ressource',
            'Resümee',
            'Revanche',
            'revanchieren',
            'Revision',
            'Rhetorik',
            'Rhythmus',
            'Rückgrat',
            'Saite',
            'Satellit',
            'Schlafittchen',
            'Schloss',
            'Schluss',
            'Schmalz',
            'schmelzen',
            'schnellstmöglich',
            'seid',
            'seit',
            'seit Kurzem',
            'selbstständig',
            'selig',
            'separat',
            'Seriosität',
            'Silhouette',
            'Silvester',
            'Sisyphusarbeit',
            'skurril',
            'Smiley',
            'sodass',
            'sogenannt',
            'Souterrain',
            'soweit',
            'sowie',
            'Spaghetti',
            'spazieren',
            'sporadisch',
            'spülen',
            'Standard',
            'stattdessen',
            'Status',
            'Stegreif',
            'Stele',
            'Strang',
            'Straße',
            'stringent',
            'Strophe',
            'subtil',
            'Symmetrie',
            'Sympathie',
            'sympathisch',
            'Terrasse',
            'Tiger',
            'Tipp',
            'todlangweilig',
            'todtraurig',
            'tolerant',
            'Toleranz',
            'Trilogie',
            'Triumph',
            'triumphieren',
            'Turnier',
            'übersät',
            'übrigens',
            'unendlich',
            'unentgeltlich',
            'unsympathisch',
            'unter anderem',
            'verhören',
            'Verlies',
            'vermeintlich',
            'verpönt',
            'Verwandtschaft',
            'verwandtschaftlich',
            'Verzeichnis',
            'vielleicht',
            'von klein auf',
            'vor allem',
            'vor Kurzem',
            'vor Ort',
            'voraus',
            'Voraussetzung',
            'voraussichtlich',
            'vorbeikommen',
            'Vorort',
            'währenddessen',
            'wahrnehmen',
            'wart',
            'weismachen',
            'weiß',
            'weißt',
            'wider',
            'widerfahren',
            'widerlegen',
            'widerspiegeln',
            'widerspiegeln',
            'Widerspruch',
            'widerstehen',
            'wiederum',
            'willkommen',
            'zartbesaitet',
            'ziemlich',
            'ziemlich',
            'zu Ende',
            'zu Hause',
            'zu viel',
            'Zucchini',
            'zugrunde liegen',
            'zugunsten',
            'zugutekommen',
            'Zuhause',
            'zum einen … zum anderen',
            'zumindest',
            'zurecht',
            'zurzeit',
            'zustande kommen',
            'zuwider',
        );
    
        return $main;
    }

    public static function getDifficultWords() {
               
        $keywords = array(
            'Polymer',
            'Polysaccharid',
            'Lymphocyten',
            "Mendel'sche Regel",
            'K+',
            'Na-K-Pumpe',
            "Guanosin-5'-triphosphat",
            'Sakroplasmatisches',
            'Retikulum',
        );
        
        return $keywords;
    }

    public static function getFillerWords() {

        $polyfill = array(
            'an',
            'sich',
            'zu',
            'lange',
            'bei',
            'am',
            'und',
            'das',
            'der',
            'die',
            'ohne',
            'ob',
        );

        return $polyfill;
    }

}